---
version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Hello World
          command: echo "Hello World!"
      - run:
          name: ls repo content
          command: pwd && ls -la

workflows:
  welcome:
    jobs:
      - job1
